name: RPGStat
main: com.Sora.RPGStat.Main
version: 1.0
description: Stat plugin!
commands:
  stat:
  스탯:
    description: §e/stat §f을 치면 자신의 스텟을 볼 수 있습니다.
  inv:
    description: 
  공지:
    description: 
  heal:
    description: 
  menu:
  메뉴:
    description: 
  거래:
    description: 